blank_issues_enabled: false
contact_links:
  - name: Getting Started Guide ğŸƒ
    url: https://www.plexripper.rocks/guides/getting-started
    about: Getting started with PlexRipper

  - name: Frequently Asked Questions ğŸ¤”
    url: https://www.plexripper.rocks/faq/
    about: Frequently Asked Questions about PlexRipper

  - name: Ask your own question â“
    url: https://github.com/PlexRipper/PlexRipper/discussions
    about: Ask a question or request support for using PlexRipper