blank_issues_enabled: false
contact_links:
  - name: Getting Started Guide ğŸƒ
    url: https://www.plexripper.rocks/guides/getting-started
    about: Documentation - information about all of our containers.

  - name: Frequently Asked Questions ğŸ¤”
    url: https://www.plexripper.rocks/faq/
    about: Frequently Asked Questions

  - name: Ask your own question â“
    url: https://github.com/PlexRipper/PlexRipper/discussions
    about: Ask a question or request support for using the template